//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KirimEmail
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Common_Request", Namespace="http://schemas.datacontract.org/2004/07/Messaging.WCF.Classes")]
    public partial class Common_Request : object
    {
        
        private string PasswordField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message_Request", Namespace="http://schemas.datacontract.org/2004/07/Messaging.WCF.Classes")]
    public partial class Message_Request : object
    {
        
        private string BccField;
        
        private string CcField;
        
        private string ContentField;
        
        private string DatetimeCreatedField;
        
        private string SubjectField;
        
        private string ToField;
        
        private string TypeMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bcc
        {
            get
            {
                return this.BccField;
            }
            set
            {
                this.BccField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cc
        {
            get
            {
                return this.CcField;
            }
            set
            {
                this.CcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatetimeCreated
        {
            get
            {
                return this.DatetimeCreatedField;
            }
            set
            {
                this.DatetimeCreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeMessage
        {
            get
            {
                return this.TypeMessageField;
            }
            set
            {
                this.TypeMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message_Response", Namespace="http://schemas.datacontract.org/2004/07/Messaging.WCF.Classes")]
    public partial class Message_Response : object
    {
        
        private string TicketIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TicketID
        {
            get
            {
                return this.TicketIDField;
            }
            set
            {
                this.TicketIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://schemas.datacontract.org/2004/07/Messaging.WCF.Classes")]
    public partial class ResponseMessage : object
    {
        
        private string CodeField;
        
        private string[] DescMsgField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DescMsg
        {
            get
            {
                return this.DescMsgField;
            }
            set
            {
                this.DescMsgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageStatus_Response", Namespace="http://schemas.datacontract.org/2004/07/Messaging.WCF.Classes")]
    public partial class MessageStatus_Response : object
    {
        
        private string DatetimeDeliveryField;
        
        private string StatusField;
        
        private string TicketIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatetimeDelivery
        {
            get
            {
                return this.DatetimeDeliveryField;
            }
            set
            {
                this.DatetimeDeliveryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TicketID
        {
            get
            {
                return this.TicketIDField;
            }
            set
            {
                this.TicketIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KirimEmail.IGeneral")]
    public interface IGeneral
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/Send_Message", ReplyAction="http://tempuri.org/IGeneral/Send_MessageResponse")]
        KirimEmail.Send_MessageResponse Send_Message(KirimEmail.Send_MessageRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/Send_Message", ReplyAction="http://tempuri.org/IGeneral/Send_MessageResponse")]
        System.Threading.Tasks.Task<KirimEmail.Send_MessageResponse> Send_MessageAsync(KirimEmail.Send_MessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/Check_Status", ReplyAction="http://tempuri.org/IGeneral/Check_StatusResponse")]
        KirimEmail.Check_StatusResponse Check_Status(KirimEmail.Check_StatusRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/Check_Status", ReplyAction="http://tempuri.org/IGeneral/Check_StatusResponse")]
        System.Threading.Tasks.Task<KirimEmail.Check_StatusResponse> Check_StatusAsync(KirimEmail.Check_StatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Send_Message", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Send_MessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public KirimEmail.Common_Request RequestCommon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public KirimEmail.Message_Request RequestData;
        
        public Send_MessageRequest()
        {
        }
        
        public Send_MessageRequest(KirimEmail.Common_Request RequestCommon, KirimEmail.Message_Request RequestData)
        {
            this.RequestCommon = RequestCommon;
            this.RequestData = RequestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Send_MessageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Send_MessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public KirimEmail.Message_Response ResponseData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public KirimEmail.ResponseMessage ResponseMsg;
        
        public Send_MessageResponse()
        {
        }
        
        public Send_MessageResponse(KirimEmail.Message_Response ResponseData, KirimEmail.ResponseMessage ResponseMsg)
        {
            this.ResponseData = ResponseData;
            this.ResponseMsg = ResponseMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Check_Status", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Check_StatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public KirimEmail.Common_Request RequestCommon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] TicketIDList;
        
        public Check_StatusRequest()
        {
        }
        
        public Check_StatusRequest(KirimEmail.Common_Request RequestCommon, string[] TicketIDList)
        {
            this.RequestCommon = RequestCommon;
            this.TicketIDList = TicketIDList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Check_StatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Check_StatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public KirimEmail.MessageStatus_Response[] ResponseData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public KirimEmail.ResponseMessage ResponseMsg;
        
        public Check_StatusResponse()
        {
        }
        
        public Check_StatusResponse(KirimEmail.MessageStatus_Response[] ResponseData, KirimEmail.ResponseMessage ResponseMsg)
        {
            this.ResponseData = ResponseData;
            this.ResponseMsg = ResponseMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IGeneralChannel : KirimEmail.IGeneral, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class GeneralClient : System.ServiceModel.ClientBase<KirimEmail.IGeneral>, KirimEmail.IGeneral
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GeneralClient() : 
                base(GeneralClient.GetDefaultBinding(), GeneralClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_IGeneral.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeneralClient(EndpointConfiguration endpointConfiguration) : 
                base(GeneralClient.GetBindingForEndpoint(endpointConfiguration), GeneralClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeneralClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GeneralClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeneralClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GeneralClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeneralClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KirimEmail.Send_MessageResponse KirimEmail.IGeneral.Send_Message(KirimEmail.Send_MessageRequest request)
        {
            return base.Channel.Send_Message(request);
        }
        
        public KirimEmail.Message_Response Send_Message(KirimEmail.Common_Request RequestCommon, KirimEmail.Message_Request RequestData, out KirimEmail.ResponseMessage ResponseMsg)
        {
            KirimEmail.Send_MessageRequest inValue = new KirimEmail.Send_MessageRequest();
            inValue.RequestCommon = RequestCommon;
            inValue.RequestData = RequestData;
            KirimEmail.Send_MessageResponse retVal = ((KirimEmail.IGeneral)(this)).Send_Message(inValue);
            ResponseMsg = retVal.ResponseMsg;
            return retVal.ResponseData;
        }
        
        public System.Threading.Tasks.Task<KirimEmail.Send_MessageResponse> Send_MessageAsync(KirimEmail.Send_MessageRequest request)
        {
            return base.Channel.Send_MessageAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KirimEmail.Check_StatusResponse KirimEmail.IGeneral.Check_Status(KirimEmail.Check_StatusRequest request)
        {
            return base.Channel.Check_Status(request);
        }
        
        public KirimEmail.MessageStatus_Response[] Check_Status(KirimEmail.Common_Request RequestCommon, string[] TicketIDList, out KirimEmail.ResponseMessage ResponseMsg)
        {
            KirimEmail.Check_StatusRequest inValue = new KirimEmail.Check_StatusRequest();
            inValue.RequestCommon = RequestCommon;
            inValue.TicketIDList = TicketIDList;
            KirimEmail.Check_StatusResponse retVal = ((KirimEmail.IGeneral)(this)).Check_Status(inValue);
            ResponseMsg = retVal.ResponseMsg;
            return retVal.ResponseData;
        }
        
        public System.Threading.Tasks.Task<KirimEmail.Check_StatusResponse> Check_StatusAsync(KirimEmail.Check_StatusRequest request)
        {
            return base.Channel.Check_StatusAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IGeneral))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IGeneral))
            {
                return new System.ServiceModel.EndpointAddress(new System.Uri("https://ptmkpwebsvc02.pertamina.com/Messaging/WCF/General/General.svc"), new System.ServiceModel.DnsEndpointIdentity("localhost"));
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GeneralClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IGeneral);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GeneralClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IGeneral);
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_IGeneral,
        }
    }
}
